apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka
  ports:
    - name: broker
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: bootstrap
      protocol: TCP
      port: 9071
      targetPort: 9071
    - name: c3
      protocol: TCP
      port: 9021
      targetPort: 9021
    - name: zk
      protocol: TCP
      port: 2181
      targetPort: 2181
